### ISSUE TITLE
Consider adding drag and drop support to NeuralCircuits

### ISSUE THREAD

**Issue by willibrandon** [SimbeyGit/simbey#2]
Hi,

I like your Neural Circuits simulator, and see that it has support for saving and opening Simbey Neural Net file types (.snn). I think it would be cool if there was also support for dragging a .snn file from Explorer, and dropping it onto the application to open file.

**Comment by willibrandon** [comment]
I believe the easiest way to implement this would be to call the [`DragAcceptFiles`](https://learn.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-dragacceptfiles) function with the `fAccept` parameter set to `TRUE` and then by processing the [`WM_DROPFILES`](https://learn.microsoft.com/en-us/windows/win32/shell/wm-dropfiles) message.

**Comment by willibrandon** [comment]
Getting closer!

![DragAcceptFiles](https://github.com/SimbeyGit/simbey/assets/5017479/301f71cd-2bde-4a0d-ab63-30f0d4e6e0c4)

**Comment by willibrandon** [comment]
What do you think?

https://github.com/SimbeyGit/simbey/assets/5017479/da456a0d-894a-49f7-81ce-726abf925cd8

I've never done that before using C++. However, I have spent a lot of time looking at that documentation.

**Comment by SimbeyGit** [comment]
That looks right.  Does it prompt for saving the previous document if there were changes?  That's a call to m_lpDoc->ChangesMade().

**Comment by willibrandon** [comment]
Yep!

![NeuralCircuitsSaveChanges](https://github.com/SimbeyGit/simbey/assets/5017479/ea6c533e-9223-4090-8e25-9eae55580d7c)

Do you actively work on Neural Circuits? I could see this being its own separate project.

**Comment by SimbeyGit** [comment]
No, I haven't really done anything to it in years, but I'll get this addition committed shortly.

**Comment by willibrandon** [comment]
Awesome.

I'm very much into learning the Windows APIs and this repo is an excellent resource. The Neural Circuits Simulator is great and I expect I'll have more questions as I learn how to use it more.

**Comment by willibrandon** [comment]
The graph control is fascinating.

**Comment by willibrandon** [comment]
This reminds me a lot of the Windows Forms designer, and I could also see this being built as a Windows Forms custom control itself, with full blown Windows Forms designer support using the designer extensibility sdk.

**Comment by willibrandon** [comment]
How did you learn how to do that? I read the documentation and run and look at as many samples as I can and I’m not accustomed to seeing something this interesting.

**Comment by SimbeyGit** [comment]
> How did you learn how to do that? I read the documentation and run and look at as many samples as I can and I’m not accustomed to seeing something this interesting.

I started working with Windows programming something like 25 years ago!  😆
